# Generated by Django 6.0.5 on 2026-05-31 10:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('hazard_type', models.CharField(choices=[('flood', 'Flood'), ('rainfall', 'Rainfall'), ('river_level', 'River level'), ('landslide', 'Landslide'), ('storm_surge', 'Storm surge'), ('seismic', 'Seismic')], max_length=20)),
                ('municipality', models.CharField(choices=[('Tacloban City', 'Tacloban City'), ('Palo', 'Palo'), ('Tanauan', 'Tanauan'), ('Tolosa', 'Tolosa'), ('Dulag', 'Dulag'), ('Abuyog', 'Abuyog'), ('Baybay City', 'Baybay City'), ('Ormoc City', 'Ormoc City'), ('Carigara', 'Carigara'), ('Barugo', 'Barugo'), ('Jaro', 'Jaro'), ('Pastrana', 'Pastrana'), ('Alangalang', 'Alangalang'), ('Santa Fe', 'Santa Fe'), ('Tabontabon', 'Tabontabon'), ('MacArthur', 'MacArthur')], max_length=120)),
                ('barangay', models.CharField(blank=True, max_length=120)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('advisory', 'Advisory'), ('watch', 'Watch'), ('warning', 'Warning'), ('critical', 'Critical')], default='normal', max_length=20)),
                ('online', models.BooleanField(default=True)),
                ('installed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['municipality', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor_name', models.CharField(blank=True, max_length=120)),
                ('action', models.CharField(max_length=80)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('flooding', 'Flooding'), ('landslide', 'Landslide'), ('road_blockage', 'Road blockage'), ('structural_damage', 'Structural damage'), ('casualty', 'Casualty'), ('evacuation', 'Evacuation'), ('power_outage', 'Power outage'), ('other', 'Other')], max_length=24)),
                ('municipality', models.CharField(choices=[('Tacloban City', 'Tacloban City'), ('Palo', 'Palo'), ('Tanauan', 'Tanauan'), ('Tolosa', 'Tolosa'), ('Dulag', 'Dulag'), ('Abuyog', 'Abuyog'), ('Baybay City', 'Baybay City'), ('Ormoc City', 'Ormoc City'), ('Carigara', 'Carigara'), ('Barugo', 'Barugo'), ('Jaro', 'Jaro'), ('Pastrana', 'Pastrana'), ('Alangalang', 'Alangalang'), ('Santa Fe', 'Santa Fe'), ('Tabontabon', 'Tabontabon'), ('MacArthur', 'MacArthur')], max_length=120)),
                ('barangay', models.CharField(blank=True, max_length=120)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('verified', 'Verified'), ('responding', 'Responding'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='reported', max_length=12)),
                ('summary', models.TextField(help_text='Internal summary for LGU staff.')),
                ('public_summary', models.TextField(blank=True, help_text='Sanitized text shown on the public feed.')),
                ('reporter_name', models.CharField(blank=True, max_length=120)),
                ('reporter_contact', models.CharField(blank=True, max_length=40)),
                ('internal_notes', models.TextField(blank=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=16)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='core.sensor')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('level', models.CharField(choices=[('information', 'Information'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('red', 'Red')], max_length=12)),
                ('hazard_type', models.CharField(choices=[('flood', 'Flood'), ('rainfall', 'Rainfall'), ('river_level', 'River level'), ('landslide', 'Landslide'), ('storm_surge', 'Storm surge'), ('seismic', 'Seismic')], max_length=20)),
                ('message', models.TextField()),
                ('municipalities', models.JSONField(default=list)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_until', models.DateTimeField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('issuing_office', models.CharField(default='MDRRMO', max_length=80)),
                ('active', models.BooleanField(default=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warnings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
    ]
