# Generated by Django 6.0.5 on 2026-05-31 11:13

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='dispatcher_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='incident',
            name='dispatcher_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='incident',
            name='dispatcher_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('reported', 'Reported'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='reported', max_length=12),
        ),
        migrations.CreateModel(
            name='HazardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.models.hazard_image_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='hazard_images/thumbs/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.incident')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
