# Generated by Django 6.0.5 on 2026-05-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'LGU Admin'), ('dispatcher', 'Dispatcher'), ('viewer', 'Public Viewer')], default='viewer', max_length=20),
        ),
    ]
